version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node
    restart: unless-stopped
    ports:
      # For the external world
      - '0.0.0.0:80:8000'
      - '0.0.0.0:443:8000'
      - '0.0.0.0:8000:8000'
      - '0.0.0.0:8001:8001'
      - '0.0.0.0:8020:8020'
      - '0.0.0.0:8030:8030'
      - '0.0.0.0:8040:8040'
    depends_on:
      - ipfs
      - postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: oTZvXetKe0tIuuIG
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      GRAPH_LOG: info
      # Important. This is our RPC node
      ethereum: 'mainnet:https://rpc-staging.10planet.com'
  ipfs:
    image: ipfs/kubo:v0.17.0
    restart: unless-stopped
    ports:
      - '5001:5001'
    volumes:
      - ./data/ipfs:/data/ipfs:Z
      
  # @todo Change this to RDS?
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements",
        "-cmax_connections=200"
      ]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: oTZvXetKe0tIuuIG
      POSTGRES_DB: graph-node
      # FIXME: remove this env. var. which we shouldn't need. Introduced by
      # <https://github.com/graphprotocol/graph-node/pull/3511>, maybe as a
      # workaround for https://github.com/docker/for-mac/issues/6270?
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:Z